export const MAP_MODE_ICONS: Record<string, string> = {
  landscape: '/assets/icons/I_Terrain.png',
  political: '/assets/icons/I_DependentFactions.png',
  overlord: '/assets/icons/I_IndependentFactions.png',
  religion: '/assets/icons/I_Religions.png',
  culture: '/assets/icons/I_Cultures.png',
  bishopric: '/assets/icons/I_Bishop.png',
  adminRegion: '/assets/icons/I_Region.png',
  adminLand: '/assets/icons/I_Land.png',
  adminDomain: '/assets/icons/I_Domain.png',
  regionGovernor: '/assets/icons/I_Characters.png',
  resources: '/assets/icons/I_Resources.png',
  trade: '/assets/icons/Treaties/I_TradeAgreement.png',
  stockpiles: '/assets/icons/I_ResourceConsumption.png',
  economicProsperity: '/assets/icons/I_Coins.png',
  population: '/assets/icons/I_Population.png',
  unrest: '/assets/icons/I_Unrest.png',
  disease: '/assets/icons/I_Skull.png',
  corruption: '/assets/traits/Corrupt.png',
  loyalty: '/assets/icons/I_Loyalty.png',
  diplomaticRelation: '/assets/icons/I_Peace.png',
  militaries: '/assets/icons/Armies/I_ArmyRephsian.png',
  garrisons: '/assets/icons/Doctrines/I_Doctrine_Garrison.png',
};
